package com.sybinal.shop.model;

import java.util.Date;
/*
* 付款历史记录    payment_history
* */
public class PaymentHistory {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column payment_history.id
	 * @mbggenerated  Wed Oct 19 21:07:43 CST 2016
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column payment_history.order_num
	 * @mbggenerated  Wed Oct 19 21:07:43 CST 2016
	 */
	private String orderNum;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column payment_history.product_price
	 * @mbggenerated  Wed Oct 19 21:07:43 CST 2016
	 */
	private Integer productPrice;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column payment_history.payment_type
	 * @mbggenerated  Wed Oct 19 21:07:43 CST 2016
	 */
	private Integer paymentType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column payment_history.user_id
	 * @mbggenerated  Wed Oct 19 21:07:43 CST 2016
	 */
	private Integer userId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column payment_history.payment_time
	 * @mbggenerated  Wed Oct 19 21:07:43 CST 2016
	 */
	private Date paymentTime;

	private String out_trade_no;
	private String subject;
	private Integer total_amount;
	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column payment_history.id
	 * @return  the value of payment_history.id
	 * @mbggenerated  Wed Oct 19 21:07:43 CST 2016
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column payment_history.id
	 * @param id  the value for payment_history.id
	 * @mbggenerated  Wed Oct 19 21:07:43 CST 2016
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column payment_history.order_num
	 * @return  the value of payment_history.order_num
	 * @mbggenerated  Wed Oct 19 21:07:43 CST 2016
	 */
	public String getOrderNum() {
		return orderNum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column payment_history.order_num
	 * @param orderNum  the value for payment_history.order_num
	 * @mbggenerated  Wed Oct 19 21:07:43 CST 2016
	 */
	public void setOrderNum(String orderNum) {
		this.orderNum = orderNum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column payment_history.product_price
	 * @return  the value of payment_history.product_price
	 * @mbggenerated  Wed Oct 19 21:07:43 CST 2016
	 */
	public Integer getProductPrice() {
		return productPrice;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column payment_history.product_price
	 * @param productPrice  the value for payment_history.product_price
	 * @mbggenerated  Wed Oct 19 21:07:43 CST 2016
	 */
	public void setProductPrice(Integer productPrice) {
		this.productPrice = productPrice;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column payment_history.payment_type
	 * @return  the value of payment_history.payment_type
	 * @mbggenerated  Wed Oct 19 21:07:43 CST 2016
	 */
	public Integer getPaymentType() {
		return paymentType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column payment_history.payment_type
	 * @param paymentType  the value for payment_history.payment_type
	 * @mbggenerated  Wed Oct 19 21:07:43 CST 2016
	 */
	public void setPaymentType(Integer paymentType) {
		this.paymentType = paymentType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column payment_history.user_id
	 * @return  the value of payment_history.user_id
	 * @mbggenerated  Wed Oct 19 21:07:43 CST 2016
	 */
	public Integer getUserId() {
		return userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column payment_history.user_id
	 * @param userId  the value for payment_history.user_id
	 * @mbggenerated  Wed Oct 19 21:07:43 CST 2016
	 */
	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column payment_history.payment_time
	 * @return  the value of payment_history.payment_time
	 * @mbggenerated  Wed Oct 19 21:07:43 CST 2016
	 */
	public Date getPaymentTime() {
		return paymentTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column payment_history.payment_time
	 * @param paymentTime  the value for payment_history.payment_time
	 * @mbggenerated  Wed Oct 19 21:07:43 CST 2016
	 */
	public void setPaymentTime(Date paymentTime) {
		this.paymentTime = paymentTime;
	}

	public String getOut_trade_no() {
		return out_trade_no;
	}

	public void setOut_trade_no(String out_trade_no) {
		this.out_trade_no = out_trade_no;
	}

	public String getSubject() {
		return subject;
	}

	public void setSubject(String subject) {
		this.subject = subject;
	}

	public Integer getTotal_amount() {
		return total_amount;
	}

	public void setTotal_amount(Integer total_amount) {
		this.total_amount = total_amount;
	}
}